# 服务器端口
server.port=8081

# 应用名称
spring.application.name=demo

# 日志级别
logging.level.com.example.demo=DEBUG

# MySQL 8.0 配置
spring.datasource.url=jdbc:mysql://www.scushujin.xyz:3306/traffic?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=33947602Bty!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JDBC 配置
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# 文件上传配置
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 伴车星GPS配置
bcx.cookie-randTID=randTID1=616169_592035_569381_539926_636431_622031_615785_576791_187258_614076_634646_623682_639299_586842_427838_330106_580100_588971_578425_512865_640253_629890_586240_614465_544048; randTIDGkey=-1rs5057ovdji4c5ajulbo052kqfnnl5t
bcx.cookie-url=http://www.bcxgps.com/page/login/BcxLoad.action?r=g
# 可选：JSESSIONID刷新间隔（小时）0表示不自动刷新
bcx.session-refresh-hours=24

# 百度车牌识别api配置
baidu.ocr.api-key=4bXKfBNSVWLLpzjxTpaduU3H
baidu.ocr.secret-key=Db6Jg2uwJlOB2Axg9PrfbuUw9SicpuPy
baidu.ocr.connect-timeout=60000
baidu.ocr.read-timeout=300000

# 上传文件路径
upload.path=C:/Users/35494/IdeaProjects/SmartTraffic/uploads
# 逆行处理后路径配置
capture.image.dir=D:/PyCharm/wrong-way-vehicle-detection/yolov5/cars
# 压线抓拍路径配置
capture.image.dir.line_press=D:/PyCharm/Line-pressure-detection/cars
# 违停抓拍路径配置
capture.image.dir.illegal_parking=D:/PyCharm/Road-occupancy-operation-and-vehicle-illegal-parking-detection-main/cars
# 图片保存路径配置
car.image.save.dir=C:/Users/35494/IdeaProjects/SmartTraffic/save
