spring.application.name=demo

spring.datasource.url=jdbc:mysql://www.scushujin.xyz:3306/gym_system
spring.datasource.username=root
spring.datasource.password=33947602Bty!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver